### ISSUE TITLE
panic: pebble: batch too large

### ISSUE THREAD

**Issue by baabeetaa** [notional-labs/cosmprund#11]
```
panic: pebble: batch too large: >= 4.0 G

goroutine 733 [running]:
github.com/cockroachdb/pebble.(*Batch).grow(0x0?, 0x418bff?)
	/root/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20220726134658-7b78c71e4055/batch.go:1108 +0x129
github.com/cockroachdb/pebble.(*Batch).prepareDeferredKeyRecord(0xc00311cfc0, 0x32, 0x0)
	/root/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20220726134658-7b78c71e4055/batch.go:498 +0x74
github.com/cockroachdb/pebble.(*Batch).DeleteDeferred(...)
	/root/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20220726134658-7b78c71e4055/batch.go:600
github.com/cockroachdb/pebble.(*Batch).Delete(0xc00311cfc0?, {0xc0b69d6dc0?, 0x32?, 0xc0b69d6dc0?}, 0xc0b69dc750?)
	/root/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20220726134658-7b78c71e4055/batch.go:583 +0x31
github.com/tendermint/tm-db.(*pebbleDBBatch).Delete(0x11?, {0xc0b69d6dc0?, 0xc006a03800?, 0x459bd2?})
	/root/go/pkg/mod/github.com/baabeetaa/tm-db@v0.6.7-0.20220728101401-7c0a33fd88c8/pebble.go:283 +0x2e
github.com/tendermint/tm-db.prefixDBBatch.Delete({{0xc003696d68, 0x11, 0x18}, {0x1568f40, 0xc005a5e270}}, {0xc0b69e6030, 0x21, 0xc000100400?})
	/root/go/pkg/mod/github.com/baabeetaa/tm-db@v0.6.7-0.20220728101401-7c0a33fd88c8/prefixdb_batch.go:35 +0x117
github.com/cosmos/iavl.(*nodeDB).DeleteVersionsRange.func1({0xc0b69e4511, 0x31, 0x31}, {0xc0b69d0b00, 0x20, 0x20})
	/root/go/pkg/mod/github.com/cosmos/iavl@v0.17.3/nodedb.go:305 +0x1e4
github.com/cosmos/iavl.(*nodeDB).traversePrefix(0xc000e84b10?, {0xc0b69880d0?, 0x1?, 0x1?}, 0xc006a03c00)
	/root/go/pkg/mod/github.com/cosmos/iavl@v0.17.3/nodedb.go:521 +0x112
github.com/cosmos/iavl.(*nodeDB).traverseOrphansVersion(0xc0022c87e0?, 0xc005fd1b80?, 0x4d2774?)
	/root/go/pkg/mod/github.com/cosmos/iavl@v0.17.3/nodedb.go:487 +0x6e
github.com/cosmos/iavl.(*nodeDB).DeleteVersionsRange(0xc0022c87e0, 0x1cd8a0, 0x205b6c)
	/root/go/pkg/mod/github.com/cosmos/iavl@v0.17.3/nodedb.go:298 +0x457
github.com/cosmos/iavl.(*MutableTree).DeleteVersionsRange(0xc0003e2460, 0x1cd8a0, 0x205b6c)
	/root/go/pkg/mod/github.com/cosmos/iavl@v0.17.3/mutable_tree.go:623 +0x4a
github.com/cosmos/iavl.(*MutableTree).DeleteVersions(0x1559d80?, {0xc01933c000?, 0x382cc, 0x382d6})
	/root/go/pkg/mod/github.com/cosmos/iavl@v0.17.3/mutable_tree.go:611 +0x2ca
github.com/cosmos/cosmos-sdk/store/iavl.(*Store).DeleteVersions(...)
	/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.2-0.20220209090836-4161d2b6022a/store/iavl/store.go:201
github.com/binaryholdings/cosmos-pruner/internal/rootmulti.(*Store).PruneStores.func1({0x155bae0, 0xc0083953a0?})
	/root/cosmprund/internal/rootmulti/store.go:453 +0x159
created by github.com/binaryholdings/cosmos-pruner/internal/rootmulti.(*Store).PruneStores
	/root/cosmprund/internal/rootmulti/store.go:450 +0x225
```

**Comment by baabeetaa** [comment]
this is kujira snapshot
